FROM node:14-alpine

WORKDIR /portfolio

COPY ./portfolio/package.json .
COPY ./portfolio/yarn.lock .

RUN apk update && apk --no-cache add automake autoconf libtool gcc make g++ zlib-dev nasm && yarn install

COPY ./portfolio .

RUN yarn clean

EXPOSE 3000 40000
